# Generated by Django 3.0.10 on 2024-12-04 01:54

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['order', '-id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GuideFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_price_list', models.BooleanField(default=False)),
                ('downloadable_file', models.FileField(upload_to='downloadable_files')),
            ],
        ),
        migrations.CreateModel(
            name='HowWeRollPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=320)),
                ('subtitle', models.CharField(blank=True, max_length=550, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/how_we_roll')),
            ],
            options={
                'verbose_name': 'How We Roll Point',
                'verbose_name_plural': 'How We Roll Points',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(blank=True, max_length=120, null=True)),
                ('icon', models.ImageField(null=True, upload_to='images/languages')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('active', models.BooleanField(default=True)),
                ('email_address', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Member',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryFreeAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionaryReceiveOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('subtitle', models.CharField(blank=True, max_length=120, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/services')),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('telephone', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_read_more_link', models.CharField(blank=True, max_length=320, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('order', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='slides')),
                ('subtitle', models.CharField(blank=True, max_length=240, null=True)),
                ('button_text', models.CharField(blank=True, max_length=120, null=True)),
                ('button_link', models.CharField(blank=True, max_length=220, null=True)),
                ('second_button_text', models.CharField(blank=True, max_length=120, null=True)),
                ('second_button_link', models.CharField(blank=True, max_length=220, null=True)),
            ],
            options={
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial category',
                'verbose_name_plural': 'Testimonial categories',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('order', models.IntegerField()),
                ('subtitle', models.CharField(blank=True, max_length=550, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('top_story', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('slide', models.ImageField(blank=True, null=True, upload_to='images/reviews')),
                ('reviewer', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/reviewer')),
                ('stars', models.IntegerField(blank=True, help_text='From 1 to 5 stars rating if needed', null=True)),
                ('category', models.ManyToManyField(to='functionalvibes.TestimonialCategories')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('position', models.CharField(blank=True, max_length=120, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/team')),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('telephone', models.CharField(blank=True, max_length=120, null=True)),
                ('facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=120, null=True)),
                ('instagram', models.CharField(blank=True, max_length=120, null=True)),
                ('language', models.ManyToManyField(blank=True, to='functionalvibes.Language')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title')),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='blog')),
                ('hits', models.IntegerField(default=0)),
                ('body', models.TextField(verbose_name='Post body')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='post date')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='modified')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberVideoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibes_in_action', models.BooleanField(default=False)),
                ('members_area', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Video area',
                'verbose_name_plural': 'Video areas',
                'unique_together': {('vibes_in_action', 'members_area')},
            },
        ),
        migrations.CreateModel(
            name='MemberVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=550, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vimeo', models.CharField(blank=True, max_length=550, null=True)),
                ('youtube', models.CharField(blank=True, max_length=550, null=True)),
                ('display_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functionalvibes.MemberVideoArea')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='GuideQuestionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True)),
                ('maximize_effectiveness_of_my_training', models.BooleanField(default=False)),
                ('get_back_in_shape', models.BooleanField(default=False)),
                ('learn_how_to_exercise_on_my_own', models.BooleanField(default=False)),
                ('need_motivation_and_accountability', models.BooleanField(default=False)),
                ('have_a_specific_injury_or_condition', models.BooleanField(default=False)),
                ('have_a_specific_goal_sport_or_event', models.BooleanField(default=False)),
                ('want_supervision_and_support', models.BooleanField(default=False)),
                ('agree_to_receive_other_communications', models.BooleanField(default=False)),
                ('get_a_free_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functionalvibes.QuestionaryFreeAssessment')),
                ('receive_an_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functionalvibes.QuestionaryReceiveOffer')),
            ],
            options={
                'verbose_name': '04 Questionary',
                'verbose_name_plural': '04 Questionaries',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('message', models.TextField(max_length=1020)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '01 Contact request',
                'verbose_name_plural': '01 Contact requests',
            },
        ),
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event', models.CharField(blank=True, max_length=80, null=True)),
                ('comments', models.TextField(blank=True, max_length=1020, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '03 event participation',
                'verbose_name_plural': '03 event participations',
            },
        ),
        migrations.CreateModel(
            name='BookCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('coach', models.CharField(blank=True, max_length=80, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_requested', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, max_length=1020, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '02 Coach request',
                'verbose_name_plural': '02 Coach request',
            },
        ),
    ]
