# Generated by Django 3.0.10 on 2024-12-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibes', '0002_auto_20241207_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideP',
            new_name='Slide',
        ),
    ]
