# Generated by Django 3.0.10 on 2020-10-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
