# Generated by Django 3.0.10 on 2020-10-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_events', '0002_auto_20201010_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
    ]
