# Generated by Django 3.0.10 on 2024-12-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
