# Generated by Django 3.0.10 on 2020-09-28 22:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=120)),
                ('photo', models.ImageField(null=True, upload_to='images/team')),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=120)),
                ('facebook', models.CharField(max_length=120)),
                ('twitter', models.CharField(max_length=120)),
                ('linkedin', models.CharField(max_length=120)),
                ('instagram', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
            },
        ),
    ]
