# Generated by Django 3.0.10 on 2020-09-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/languages'),
        ),
    ]
