# Generated by Django 3.0.10 on 2020-09-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0002_language_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
