# Generated by Django 3.0.10 on 2020-09-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0005_auto_20200929_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='language',
            field=models.ManyToManyField(blank=True, to='functionalvibes.Language'),
        ),
    ]
