# Generated by Django 3.0.10 on 2020-09-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0006_teammember_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('subtitle', models.CharField(blank=True, max_length=550, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('top_story', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('slide', models.ImageField(blank=True, null=True, upload_to='images/reviews')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/reviewer')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
