# Generated by Django 3.0.10 on 2020-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
