# Generated by Django 3.0.10 on 2020-09-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0009_testimonial_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(blank=True, help_text='From 1 to 5 stars rating if needed', null=True),
        ),
    ]
