# Generated by Django 3.0.10 on 2020-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0010_testimonial_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=550, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vimeo', models.CharField(blank=True, max_length=550, null=True)),
                ('youtube', models.CharField(blank=True, max_length=550, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
