# Generated by Django 3.0.10 on 2020-10-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0012_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowWeRollPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=320)),
                ('subtitle', models.CharField(blank=True, max_length=550, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('how_we_roll', models.ImageField(blank=True, null=True, upload_to='images/how_we_roll')),
            ],
            options={
                'verbose_name': 'How We Roll Point',
                'verbose_name_plural': 'How We Roll Points',
            },
        ),
    ]
