# Generated by Django 3.0.10 on 2020-10-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0013_howwerollpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='howwerollpoint',
            old_name='how_we_roll',
            new_name='image',
        ),
    ]
