# Generated by Django 3.0.10 on 2020-10-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0014_auto_20201003_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial category',
                'verbose_name_plural': 'Testimonial categories',
            },
        ),
    ]
