# Generated by Django 3.0.10 on 2020-10-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0015_testimonialcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functionalvibes.TestimonialCategories'),
        ),
    ]
