# Generated by Django 3.0.10 on 2020-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0017_auto_20201004_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
