# Generated by Django 3.0.10 on 2020-10-04 19:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0018_auto_20201004_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='title')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('subtitle', models.CharField(blank=True, max_length=120, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/services')),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('telephone', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
