# Generated by Django 3.0.10 on 2020-10-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0022_bookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcoach',
            name='comments',
            field=models.TextField(blank=True, max_length=1020, null=True),
        ),
    ]
