# Generated by Django 3.0.10 on 2020-10-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0023_auto_20201010_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='comments',
            field=models.TextField(blank=True, max_length=1020, null=True),
        ),
    ]
