# Generated by Django 3.0.10 on 2021-02-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0024_auto_20201010_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberVideoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibes_in_action', models.BooleanField(default=False)),
                ('members_area', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Video area',
                'verbose_name_plural': 'Video areas',
                'unique_together': {('vibes_in_action', 'members_area')},
            },
        ),
        migrations.AddField(
            model_name='membervideo',
            name='display_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functionalvibes.MemberVideoArea'),
        ),
    ]
