# Generated by Django 3.0.10 on 2021-09-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0027_auto_20210908_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidequestionary',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
