# Generated by Django 3.0.10 on 2021-09-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0028_guidequestionary_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('downloadable_file', models.FileField(upload_to='downloadable_files')),
            ],
        ),
    ]
