# Generated by Django 3.0.10 on 2021-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0030_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='first_name',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribe',
            name='last_name_name',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
