# Generated by Django 3.0.10 on 2021-09-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0031_auto_20210911_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='last_name_name',
            new_name='last_name',
        ),
    ]
