# Generated by Django 3.2.25 on 2024-06-18 00:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0035_auto_20240618_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug-test', editable=True, populate_from='title'),
            preserve_default=False,
        ),
    ]
