# Generated by Django 3.2.25 on 2024-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0037_auto_20240622_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidefile',
            name='is_price_list',
            field=models.BooleanField(default=False),
        ),
    ]
