# Generated by Django 3.2.25 on 2024-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalvibesit', '0039_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custom_read_more_link',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
